title: Web Literacy Core Curriculum
subtitle:
email:
twitter:
chat:
description: > # this means to ignore newlines until "baseurl:"
  Web literacy core curriculum
baseurl: "/web-lit-core" # the subpath of your site, e.g. /blog
url: "https://mozilla.github.io" # the base hostname & protocol for your site
github:
  repo: "mozilla/web-lit-core"
  branch: "gh-pages"


collections:
  articles:
    output: true
    permalink: /:path/

# Build settings
markdown: kramdown

redcarpet:
    extensions: [
        'no_intra_emphasis',
        'fenced_code_blocks',
        'autolink',
        'strikethrough',
        'superscript',
        'with_toc_data',
        'tables',
        'hardwrap'
    ]
